# Generated by Django 5.0.6 on 2024-06-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='roles',
        ),
        migrations.AddField(
            model_name='role',
            name='role_permissions',
            field=models.ManyToManyField(related_name='permission', to='custom_users.permission'),
        ),
    ]
