# Generated by Django 5.0.6 on 2024-06-07 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0004_alter_role_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_users.role'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='model_name',
            field=models.CharField(choices=[('cum', 'Custom User Model')], max_length=127),
        ),
    ]
